version: '3.8'

services:
  dev:
    container_name: backend
    image: backend:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn run start:dev
    ports:
      - 3000:3000
    networks:
      - mylib
    volumes:
      - ./.env:/opt/app/.env
    restart: unless-stopped

networks:
  mylib: